### ISSUE TITLE
Decrease snap threshold to 20% -  30%

### ISSUE THREAD

**Issue by dortzur** [filamentgroup/snapper#21]
Currently you only snap to the next slide if the current slide is dragged all tge way to the middle. This results jn unintentional "snap backs." decreasing default sensitivity to 20% - 30%  would be more natural. Also making it configurable it isn't already. 
Cool project.

**Comment by piyushchauhan2011** [comment]
Almost a year and no progress ?

**Comment by scottjehl** [comment]
We agree this would be ideal, but implementing it would mean adding more complicated logic to detect direction and momentum to determine intent. Currently, the script simply listens for the scroll event to stop and then snaps to the nearest snap point, regardless of which direction you scrolled. This is admittedly much less sophisticated and smooth than a native implementation, but since CSS snap point browser support is good and improving, we are comfortable with this as the fallback behavior that will be steadily replaced. Anyway, thank you for the idea. We agree it'd be better, but would not like to add the logic to support it for non-snap points browsers at this time.
